package mdpdf

import (
	"github.com/gin-gonic/gin"
)

type Handler struct{}

func RegisterRoutes(rg *gin.RouterGroup) {
	h := &Handler{}
	rg.POST("/convert", h.Convert)
	rg.POST("/render", h.Render)
}

// Convert returns a PDF binary generated by headless Chromium.
func (h *Handler) Convert(c *gin.Context) {
	var req ConvertRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(400, gin.H{"error": err.Error()})
		return
	}
	if req.Markdown == "" {
		c.JSON(400, gin.H{"error": "markdown is required"})
		return
	}

	pdf, err := ConvertToPDF(req)
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}

	c.Header("Content-Type", "application/pdf")
	c.Header("Content-Disposition", `attachment; filename="document.pdf"`)
	c.Data(200, "application/pdf", pdf)
}

// Render returns the styled HTML document (used by the frontend print fallback).
func (h *Handler) Render(c *gin.Context) {
	var req ConvertRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(400, gin.H{"error": err.Error()})
		return
	}
	if req.Markdown == "" {
		c.JSON(400, gin.H{"error": "markdown is required"})
		return
	}

	rendered, err := RenderHTML(req)
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}

	c.Header("Content-Type", "text/html; charset=utf-8")
	c.String(200, rendered)
}